### ISSUE TITLE
pkg-config does not find dependencies in library_install_prefix

### ISSUE THREAD

**Issue by swnf** [pyodide/pyodide-build#51]
### Problem

In my build scripts, `pkg-config` could not find the dependencies in `library_install_prefix` as expected. It seems like pyodide-build tries to configure `pkg-config` here:

https://github.com/pyodide/pyodide-build/blob/4805d73e37e8448b7937faeb663bd8e450125417/pyodide_build/buildpkg.py#L552-L554

But in a call to `emconfigure ./configure ...` emscripten will [override this variable](https://github.com/emscripten-core/emscripten/blob/47b9540aa4364d5c1bde36859f03473d1f926838/tools/building.py#L65-L66).

### Proposed solution

I think it is necessary to set `EM_PKG_CONFIG_PATH`. This can be done in addition to `PKG_CONFIG_LIBDIR`. I'm unsure if the existing `PKG_CONFIG_LIBDIR` has any observable effect.

**Comment by hoodmane** [comment]
Sounds reasonable, PR welcome.

**Comment by swnf** [comment]
I've created PR #52 for this issue.
